

GET http://127.0.0.1:5000/customer

###

GET http://127.0.0.1:5000/appointment


###

GET http://127.0.0.1:5000/getAppointments


###

GET http://127.0.0.1:5000/home


###
GET http://127.0.0.1:5000/total_customers

###
GET http://127.0.0.1:5000/total_staff

###
GET http://127.0.0.1:5000/total_services


###
GET http://127.0.0.1:5000/total_bills


###
POST http://127.0.0.1:5000/contact_us
Content-Type: application/json

{
  "FirstName": "hafsa",
  "LastName": "Khan",
  "Email_id": "hafsakhan12@gmail.com",
  "Message": "hello"
}


###
GET http://127.0.0.1:5000/appointment


###
GET http://127.0.0.1:5000/unread_messages


###

GET http://127.0.0.1:5000/total_feedbacks

